name: Publish .NET Library

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/DapperContext/DapperContext.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/DapperContext/DapperContext.csproj

    - name: Create NuGet package
      run: dotnet pack --configuration Release --no-restore ./src/DapperContext/DapperContext.csproj

    - name: Publish to GitHub Packages
      if: github.ref == 'refs/heads/master'
      env:
        TOKENWRITE: ${{ secrets.TOKENWRITE }}
      run: |
        $token = $env:TOKENWRITE
        dotnet nuget push **/*.nupkg --source "https://nuget.pkg.github.com/FrattaMarco/index.json" --api-key $token
